/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YieldPredictionRouteImport } from './routes/yield-prediction'
import { Route as WeatherIntelligenceRouteImport } from './routes/weather-intelligence'
import { Route as WaterManagementRouteImport } from './routes/water-management'
import { Route as VillageDashboardRouteImport } from './routes/village-dashboard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PestMonitoringRouteImport } from './routes/pest-monitoring'
import { Route as NutrientAnalysisRouteImport } from './routes/nutrient-analysis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveMonitoringRouteImport } from './routes/live-monitoring'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as HarvestPlannerRouteImport } from './routes/harvest-planner'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FarmOverviewRouteImport } from './routes/farm-overview'
import { Route as DroneMonitoringRouteImport } from './routes/drone-monitoring'
import { Route as DiseaseDetectionRouteImport } from './routes/disease-detection'
import { Route as CommunityFarmsRouteImport } from './routes/community-farms'
import { Route as AiCropDoctorRouteImport } from './routes/ai-crop-doctor'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const YieldPredictionRoute = YieldPredictionRouteImport.update({
  id: '/yield-prediction',
  path: '/yield-prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherIntelligenceRoute = WeatherIntelligenceRouteImport.update({
  id: '/weather-intelligence',
  path: '/weather-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterManagementRoute = WaterManagementRouteImport.update({
  id: '/water-management',
  path: '/water-management',
  getParentRoute: () => rootRouteImport,
} as any)
const VillageDashboardRoute = VillageDashboardRouteImport.update({
  id: '/village-dashboard',
  path: '/village-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PestMonitoringRoute = PestMonitoringRouteImport.update({
  id: '/pest-monitoring',
  path: '/pest-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrientAnalysisRoute = NutrientAnalysisRouteImport.update({
  id: '/nutrient-analysis',
  path: '/nutrient-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMonitoringRoute = LiveMonitoringRouteImport.update({
  id: '/live-monitoring',
  path: '/live-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HarvestPlannerRoute = HarvestPlannerRouteImport.update({
  id: '/harvest-planner',
  path: '/harvest-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmOverviewRoute = FarmOverviewRouteImport.update({
  id: '/farm-overview',
  path: '/farm-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DroneMonitoringRoute = DroneMonitoringRouteImport.update({
  id: '/drone-monitoring',
  path: '/drone-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseDetectionRoute = DiseaseDetectionRouteImport.update({
  id: '/disease-detection',
  path: '/disease-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityFarmsRoute = CommunityFarmsRouteImport.update({
  id: '/community-farms',
  path: '/community-farms',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCropDoctorRoute = AiCropDoctorRouteImport.update({
  id: '/ai-crop-doctor',
  path: '/ai-crop-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-crop-doctor': typeof AiCropDoctorRoute
  '/community-farms': typeof CommunityFarmsRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/drone-monitoring': typeof DroneMonitoringRoute
  '/farm-overview': typeof FarmOverviewRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/harvest-planner': typeof HarvestPlannerRoute
  '/landing': typeof LandingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/nutrient-analysis': typeof NutrientAnalysisRoute
  '/pest-monitoring': typeof PestMonitoringRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/village-dashboard': typeof VillageDashboardRoute
  '/water-management': typeof WaterManagementRoute
  '/weather-intelligence': typeof WeatherIntelligenceRoute
  '/yield-prediction': typeof YieldPredictionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-crop-doctor': typeof AiCropDoctorRoute
  '/community-farms': typeof CommunityFarmsRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/drone-monitoring': typeof DroneMonitoringRoute
  '/farm-overview': typeof FarmOverviewRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/harvest-planner': typeof HarvestPlannerRoute
  '/landing': typeof LandingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/nutrient-analysis': typeof NutrientAnalysisRoute
  '/pest-monitoring': typeof PestMonitoringRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/village-dashboard': typeof VillageDashboardRoute
  '/water-management': typeof WaterManagementRoute
  '/weather-intelligence': typeof WeatherIntelligenceRoute
  '/yield-prediction': typeof YieldPredictionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-crop-doctor': typeof AiCropDoctorRoute
  '/community-farms': typeof CommunityFarmsRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/drone-monitoring': typeof DroneMonitoringRoute
  '/farm-overview': typeof FarmOverviewRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/harvest-planner': typeof HarvestPlannerRoute
  '/landing': typeof LandingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/nutrient-analysis': typeof NutrientAnalysisRoute
  '/pest-monitoring': typeof PestMonitoringRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/village-dashboard': typeof VillageDashboardRoute
  '/water-management': typeof WaterManagementRoute
  '/weather-intelligence': typeof WeatherIntelligenceRoute
  '/yield-prediction': typeof YieldPredictionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-crop-doctor'
    | '/community-farms'
    | '/disease-detection'
    | '/drone-monitoring'
    | '/farm-overview'
    | '/forgot-password'
    | '/harvest-planner'
    | '/landing'
    | '/leaderboard'
    | '/live-monitoring'
    | '/login'
    | '/nutrient-analysis'
    | '/pest-monitoring'
    | '/profile'
    | '/register'
    | '/reports'
    | '/search'
    | '/settings'
    | '/village-dashboard'
    | '/water-management'
    | '/weather-intelligence'
    | '/yield-prediction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-crop-doctor'
    | '/community-farms'
    | '/disease-detection'
    | '/drone-monitoring'
    | '/farm-overview'
    | '/forgot-password'
    | '/harvest-planner'
    | '/landing'
    | '/leaderboard'
    | '/live-monitoring'
    | '/login'
    | '/nutrient-analysis'
    | '/pest-monitoring'
    | '/profile'
    | '/register'
    | '/reports'
    | '/search'
    | '/settings'
    | '/village-dashboard'
    | '/water-management'
    | '/weather-intelligence'
    | '/yield-prediction'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-crop-doctor'
    | '/community-farms'
    | '/disease-detection'
    | '/drone-monitoring'
    | '/farm-overview'
    | '/forgot-password'
    | '/harvest-planner'
    | '/landing'
    | '/leaderboard'
    | '/live-monitoring'
    | '/login'
    | '/nutrient-analysis'
    | '/pest-monitoring'
    | '/profile'
    | '/register'
    | '/reports'
    | '/search'
    | '/settings'
    | '/village-dashboard'
    | '/water-management'
    | '/weather-intelligence'
    | '/yield-prediction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiCropDoctorRoute: typeof AiCropDoctorRoute
  CommunityFarmsRoute: typeof CommunityFarmsRoute
  DiseaseDetectionRoute: typeof DiseaseDetectionRoute
  DroneMonitoringRoute: typeof DroneMonitoringRoute
  FarmOverviewRoute: typeof FarmOverviewRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HarvestPlannerRoute: typeof HarvestPlannerRoute
  LandingRoute: typeof LandingRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LiveMonitoringRoute: typeof LiveMonitoringRoute
  LoginRoute: typeof LoginRoute
  NutrientAnalysisRoute: typeof NutrientAnalysisRoute
  PestMonitoringRoute: typeof PestMonitoringRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  VillageDashboardRoute: typeof VillageDashboardRoute
  WaterManagementRoute: typeof WaterManagementRoute
  WeatherIntelligenceRoute: typeof WeatherIntelligenceRoute
  YieldPredictionRoute: typeof YieldPredictionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yield-prediction': {
      id: '/yield-prediction'
      path: '/yield-prediction'
      fullPath: '/yield-prediction'
      preLoaderRoute: typeof YieldPredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather-intelligence': {
      id: '/weather-intelligence'
      path: '/weather-intelligence'
      fullPath: '/weather-intelligence'
      preLoaderRoute: typeof WeatherIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water-management': {
      id: '/water-management'
      path: '/water-management'
      fullPath: '/water-management'
      preLoaderRoute: typeof WaterManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/village-dashboard': {
      id: '/village-dashboard'
      path: '/village-dashboard'
      fullPath: '/village-dashboard'
      preLoaderRoute: typeof VillageDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pest-monitoring': {
      id: '/pest-monitoring'
      path: '/pest-monitoring'
      fullPath: '/pest-monitoring'
      preLoaderRoute: typeof PestMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrient-analysis': {
      id: '/nutrient-analysis'
      path: '/nutrient-analysis'
      fullPath: '/nutrient-analysis'
      preLoaderRoute: typeof NutrientAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-monitoring': {
      id: '/live-monitoring'
      path: '/live-monitoring'
      fullPath: '/live-monitoring'
      preLoaderRoute: typeof LiveMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvest-planner': {
      id: '/harvest-planner'
      path: '/harvest-planner'
      fullPath: '/harvest-planner'
      preLoaderRoute: typeof HarvestPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm-overview': {
      id: '/farm-overview'
      path: '/farm-overview'
      fullPath: '/farm-overview'
      preLoaderRoute: typeof FarmOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drone-monitoring': {
      id: '/drone-monitoring'
      path: '/drone-monitoring'
      fullPath: '/drone-monitoring'
      preLoaderRoute: typeof DroneMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease-detection': {
      id: '/disease-detection'
      path: '/disease-detection'
      fullPath: '/disease-detection'
      preLoaderRoute: typeof DiseaseDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-farms': {
      id: '/community-farms'
      path: '/community-farms'
      fullPath: '/community-farms'
      preLoaderRoute: typeof CommunityFarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-crop-doctor': {
      id: '/ai-crop-doctor'
      path: '/ai-crop-doctor'
      fullPath: '/ai-crop-doctor'
      preLoaderRoute: typeof AiCropDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiCropDoctorRoute: AiCropDoctorRoute,
  CommunityFarmsRoute: CommunityFarmsRoute,
  DiseaseDetectionRoute: DiseaseDetectionRoute,
  DroneMonitoringRoute: DroneMonitoringRoute,
  FarmOverviewRoute: FarmOverviewRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HarvestPlannerRoute: HarvestPlannerRoute,
  LandingRoute: LandingRoute,
  LeaderboardRoute: LeaderboardRoute,
  LiveMonitoringRoute: LiveMonitoringRoute,
  LoginRoute: LoginRoute,
  NutrientAnalysisRoute: NutrientAnalysisRoute,
  PestMonitoringRoute: PestMonitoringRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  VillageDashboardRoute: VillageDashboardRoute,
  WaterManagementRoute: WaterManagementRoute,
  WeatherIntelligenceRoute: WeatherIntelligenceRoute,
  YieldPredictionRoute: YieldPredictionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
