/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YieldPredictionRouteImport } from './routes/yield-prediction'
import { Route as WeatherIntelligenceRouteImport } from './routes/weather-intelligence'
import { Route as WaterManagementRouteImport } from './routes/water-management'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PestMonitoringRouteImport } from './routes/pest-monitoring'
import { Route as NutrientAnalysisRouteImport } from './routes/nutrient-analysis'
import { Route as LiveMonitoringRouteImport } from './routes/live-monitoring'
import { Route as HarvestPlannerRouteImport } from './routes/harvest-planner'
import { Route as FarmOverviewRouteImport } from './routes/farm-overview'
import { Route as DroneMonitoringRouteImport } from './routes/drone-monitoring'
import { Route as DiseaseDetectionRouteImport } from './routes/disease-detection'
import { Route as AiCropDoctorRouteImport } from './routes/ai-crop-doctor'
import { Route as IndexRouteImport } from './routes/index'

const YieldPredictionRoute = YieldPredictionRouteImport.update({
  id: '/yield-prediction',
  path: '/yield-prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherIntelligenceRoute = WeatherIntelligenceRouteImport.update({
  id: '/weather-intelligence',
  path: '/weather-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterManagementRoute = WaterManagementRouteImport.update({
  id: '/water-management',
  path: '/water-management',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PestMonitoringRoute = PestMonitoringRouteImport.update({
  id: '/pest-monitoring',
  path: '/pest-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrientAnalysisRoute = NutrientAnalysisRouteImport.update({
  id: '/nutrient-analysis',
  path: '/nutrient-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMonitoringRoute = LiveMonitoringRouteImport.update({
  id: '/live-monitoring',
  path: '/live-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const HarvestPlannerRoute = HarvestPlannerRouteImport.update({
  id: '/harvest-planner',
  path: '/harvest-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmOverviewRoute = FarmOverviewRouteImport.update({
  id: '/farm-overview',
  path: '/farm-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DroneMonitoringRoute = DroneMonitoringRouteImport.update({
  id: '/drone-monitoring',
  path: '/drone-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseDetectionRoute = DiseaseDetectionRouteImport.update({
  id: '/disease-detection',
  path: '/disease-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCropDoctorRoute = AiCropDoctorRouteImport.update({
  id: '/ai-crop-doctor',
  path: '/ai-crop-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-crop-doctor': typeof AiCropDoctorRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/drone-monitoring': typeof DroneMonitoringRoute
  '/farm-overview': typeof FarmOverviewRoute
  '/harvest-planner': typeof HarvestPlannerRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/nutrient-analysis': typeof NutrientAnalysisRoute
  '/pest-monitoring': typeof PestMonitoringRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/water-management': typeof WaterManagementRoute
  '/weather-intelligence': typeof WeatherIntelligenceRoute
  '/yield-prediction': typeof YieldPredictionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-crop-doctor': typeof AiCropDoctorRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/drone-monitoring': typeof DroneMonitoringRoute
  '/farm-overview': typeof FarmOverviewRoute
  '/harvest-planner': typeof HarvestPlannerRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/nutrient-analysis': typeof NutrientAnalysisRoute
  '/pest-monitoring': typeof PestMonitoringRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/water-management': typeof WaterManagementRoute
  '/weather-intelligence': typeof WeatherIntelligenceRoute
  '/yield-prediction': typeof YieldPredictionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-crop-doctor': typeof AiCropDoctorRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/drone-monitoring': typeof DroneMonitoringRoute
  '/farm-overview': typeof FarmOverviewRoute
  '/harvest-planner': typeof HarvestPlannerRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/nutrient-analysis': typeof NutrientAnalysisRoute
  '/pest-monitoring': typeof PestMonitoringRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/water-management': typeof WaterManagementRoute
  '/weather-intelligence': typeof WeatherIntelligenceRoute
  '/yield-prediction': typeof YieldPredictionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-crop-doctor'
    | '/disease-detection'
    | '/drone-monitoring'
    | '/farm-overview'
    | '/harvest-planner'
    | '/live-monitoring'
    | '/nutrient-analysis'
    | '/pest-monitoring'
    | '/reports'
    | '/settings'
    | '/water-management'
    | '/weather-intelligence'
    | '/yield-prediction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-crop-doctor'
    | '/disease-detection'
    | '/drone-monitoring'
    | '/farm-overview'
    | '/harvest-planner'
    | '/live-monitoring'
    | '/nutrient-analysis'
    | '/pest-monitoring'
    | '/reports'
    | '/settings'
    | '/water-management'
    | '/weather-intelligence'
    | '/yield-prediction'
  id:
    | '__root__'
    | '/'
    | '/ai-crop-doctor'
    | '/disease-detection'
    | '/drone-monitoring'
    | '/farm-overview'
    | '/harvest-planner'
    | '/live-monitoring'
    | '/nutrient-analysis'
    | '/pest-monitoring'
    | '/reports'
    | '/settings'
    | '/water-management'
    | '/weather-intelligence'
    | '/yield-prediction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCropDoctorRoute: typeof AiCropDoctorRoute
  DiseaseDetectionRoute: typeof DiseaseDetectionRoute
  DroneMonitoringRoute: typeof DroneMonitoringRoute
  FarmOverviewRoute: typeof FarmOverviewRoute
  HarvestPlannerRoute: typeof HarvestPlannerRoute
  LiveMonitoringRoute: typeof LiveMonitoringRoute
  NutrientAnalysisRoute: typeof NutrientAnalysisRoute
  PestMonitoringRoute: typeof PestMonitoringRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  WaterManagementRoute: typeof WaterManagementRoute
  WeatherIntelligenceRoute: typeof WeatherIntelligenceRoute
  YieldPredictionRoute: typeof YieldPredictionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yield-prediction': {
      id: '/yield-prediction'
      path: '/yield-prediction'
      fullPath: '/yield-prediction'
      preLoaderRoute: typeof YieldPredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather-intelligence': {
      id: '/weather-intelligence'
      path: '/weather-intelligence'
      fullPath: '/weather-intelligence'
      preLoaderRoute: typeof WeatherIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water-management': {
      id: '/water-management'
      path: '/water-management'
      fullPath: '/water-management'
      preLoaderRoute: typeof WaterManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pest-monitoring': {
      id: '/pest-monitoring'
      path: '/pest-monitoring'
      fullPath: '/pest-monitoring'
      preLoaderRoute: typeof PestMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrient-analysis': {
      id: '/nutrient-analysis'
      path: '/nutrient-analysis'
      fullPath: '/nutrient-analysis'
      preLoaderRoute: typeof NutrientAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-monitoring': {
      id: '/live-monitoring'
      path: '/live-monitoring'
      fullPath: '/live-monitoring'
      preLoaderRoute: typeof LiveMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvest-planner': {
      id: '/harvest-planner'
      path: '/harvest-planner'
      fullPath: '/harvest-planner'
      preLoaderRoute: typeof HarvestPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm-overview': {
      id: '/farm-overview'
      path: '/farm-overview'
      fullPath: '/farm-overview'
      preLoaderRoute: typeof FarmOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drone-monitoring': {
      id: '/drone-monitoring'
      path: '/drone-monitoring'
      fullPath: '/drone-monitoring'
      preLoaderRoute: typeof DroneMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease-detection': {
      id: '/disease-detection'
      path: '/disease-detection'
      fullPath: '/disease-detection'
      preLoaderRoute: typeof DiseaseDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-crop-doctor': {
      id: '/ai-crop-doctor'
      path: '/ai-crop-doctor'
      fullPath: '/ai-crop-doctor'
      preLoaderRoute: typeof AiCropDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCropDoctorRoute: AiCropDoctorRoute,
  DiseaseDetectionRoute: DiseaseDetectionRoute,
  DroneMonitoringRoute: DroneMonitoringRoute,
  FarmOverviewRoute: FarmOverviewRoute,
  HarvestPlannerRoute: HarvestPlannerRoute,
  LiveMonitoringRoute: LiveMonitoringRoute,
  NutrientAnalysisRoute: NutrientAnalysisRoute,
  PestMonitoringRoute: PestMonitoringRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  WaterManagementRoute: WaterManagementRoute,
  WeatherIntelligenceRoute: WeatherIntelligenceRoute,
  YieldPredictionRoute: YieldPredictionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
